In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/Telco_Customer_Churn.csv")

In [3]:
df_clean = df.copy()

In [4]:
df_clean.nunique()

CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6531
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

In [5]:
for column in df_clean.columns:
    if df_clean[column].nunique() == 1:
        print(column)

Count
Country
State

In [6]:
columns_to_drop = [
    "CustomerID",
    "Count",
    "Country",
    "State"
]

df_clean = df_clean.drop(columns=columns_to_drop)

In [7]:
df_clean.shape

(7043, 29)

In [8]:
df_clean[["Churn Label", "Churn Value", "Churn Score", "Churn Reason"]].head(10)

,Churn Label,Churn Value,Churn Score,Churn Reason
0,Yes,1,86,Competitor made better offer
1,Yes,1,67,Moved
2,Yes,1,86,Moved
3,Yes,1,84,Moved
4,Yes,1,89,Competitor had better devices
5,Yes,1,78,Competitor offered higher download speeds
6,Yes,1,100,Competitor offered more data
7,Yes,1,92,Competitor made better offer
8,Yes,1,77,Competitor had better devices
9,Yes,1,97,Competitor had better devices

In [9]:
pd.crosstab(df_clean["Churn Label"], df_clean["Churn Value"])

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [10]:
df_clean["Churn Score"].describe()

count    7043.000000
mean       58.699418
std        21.525131
min         5.000000
25%        40.000000
50%        61.000000
75%        75.000000
max       100.000000
Name: Churn Score, dtype: float64

In [11]:
df_clean[["Churn Score", "Churn Reason"]].head(10)

   Churn Score                               Churn Reason
0           86               Competitor made better offer
1           67                                      Moved
2           86                                      Moved
3           84                                      Moved
4           89              Competitor had better devices
5           78  Competitor offered higher download speeds
6          100               Competitor offered more data
7           92               Competitor made better offer
8           77              Competitor had better devices
9           97              Competitor had better devices

In [12]:
columns_to_drop = [
    "Churn Label",
    "Churn Score",
    "Churn Reason",
    "CLTV"
]
df_clean = df_clean.drop(columns=columns_to_drop)

In [14]:
print("Unique Cities:", df_clean["City"].nunique())
print("Unique Zip Codes:", df_clean["Zip Code"].nunique())

Unique Cities: 1129
Unique Zip Codes: 1652

In [15]:
location_columns = [
    "City",
    "Zip Code",
    "Longitude",
    "Latitude",
    "Lat Long"
]

df_clean = df_clean.drop(columns=location_columns)

In [16]:
df_clean.shape

(7043, 20)

In [17]:
df_clean.dtypes

Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges            str
Churn Value            int64
dtype: object

In [19]:
categorical_columns = df_clean.select_dtypes(include=["object", "string"]).columns
print(categorical_columns)

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges'],
      dtype='str')

In [21]:
for col in categorical_columns:
    print(f"\n{col}")
    print(df_clean[col].unique())
    print("-" * 50)

Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
--------------------------------------------------

Senior Citizen
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Partner
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Dependents
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Phone Service
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------

Multiple Lines
<ArrowStringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str
--------------------------------------------------

Internet Service
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
--------------------------------------------------

Online Security
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Online Backup
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Device Protection
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Tech Support
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Streaming TV
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Streaming Movies
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Contract
<ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str
--------------------------------------------------

Paperless Billing
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------

Payment Method
<ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
--------------------------------------------------

Total Charges
<ArrowStringArray>
[ '108.15',  '151.65',   '820.5', '3046.05',  '5036.3',  '528.35',   '39.65',
   '20.15', '4749.15',    '30.2',
 ...
   '39.25',  '3316.1', '2625.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',
  '7362.9',  '346.45',  '6844.5']
Length: 6531, dtype: str
--------------------------------------------------

In [22]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   str
 1   Senior Citizen     7043 non-null   str
 2   Partner            7043 non-null   str
 3   Dependents         7043 non-null   str
 4   Tenure Months      7043 non-null   int64
 5   Phone Service      7043 non-null   str
 6   Multiple Lines     7043 non-null   str
 7   Internet Service   7043 non-null   str
 8   Online Security    7043 non-null   str
 9   Online Backup      7043 non-null   str
 10  Device Protection  7043 non-null   str
 11  Tech Support       7043 non-null   str
 12  Streaming TV       7043 non-null   str
 13  Streaming Movies   7043 non-null   str
 14  Contract           7043 non-null   str
 15  Paperless Billing  7043 non-null   str
 16  Payment Method     7043 non-null   str
 17  Monthly Charges    7043 non-null   float64
 18  Total Charges      7043 non-null   str
 19  Churn Value        7043 non-null   int64
dtypes: float64(1), int64(2), str(17)
memory usage: 1.7 MB

In [23]:
df_clean["Total Charges"].head(10)

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: str

In [24]:
df_clean["Total Charges"].tail(10)

7033      39.25
7034     3316.1
7035    2625.25
7036     1495.1
7037      743.3
7038     1419.4
7039     1990.5
7040     7362.9
7041     346.45
7042     6844.5
Name: Total Charges, dtype: str

In [25]:
df_clean[df_clean["Total Charges"] == " "]

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
2234,Female,No,Yes,No,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,0
2438,Male,No,No,No,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,0
2568,Female,No,Yes,No,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,0
2667,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,0
2856,Female,No,Yes,No,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,0
4331,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,0
4687,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,0
5104,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,0
5719,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,0
6772,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,0
6840,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,0

In [26]:
df_clean["Total Charges"] = pd.to_numeric(df_clean["Total Charges"], errors="coerce")

In [27]:
df_clean["Total Charges"].dtype

dtype('float64')

In [28]:
df_clean["Total Charges"].isnull().sum()

np.int64(11)

In [29]:
df_clean[df_clean["Total Charges"].isnull()]

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value
2234,Female,No,Yes,No,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,0
2438,Male,No,No,No,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,0
2568,Female,No,Yes,No,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,0
2667,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,0
2856,Female,No,Yes,No,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,0
4331,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,0
4687,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,0
5104,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,0
5719,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,0
6772,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,0
6840,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,0

In [30]:
df_clean = df_clean.dropna(subset=["Total Charges"])

In [31]:
df_clean.isnull().sum()

Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Value          0
dtype: int64

In [32]:
df_clean.shape

(7032, 20)

In [33]:
for col in categorical_columns:
    print(f"{col}: {df_clean[col].nunique()} unique values")

Gender: 2 unique values
Senior Citizen: 2 unique values
Partner: 2 unique values
Dependents: 2 unique values
Phone Service: 2 unique values
Multiple Lines: 3 unique values
Internet Service: 3 unique values
Online Security: 3 unique values
Online Backup: 3 unique values
Device Protection: 3 unique values
Tech Support: 3 unique values
Streaming TV: 3 unique values
Streaming Movies: 3 unique values
Contract: 3 unique values
Paperless Billing: 2 unique values
Payment Method: 4 unique values
Total Charges: 6530 unique values

In [35]:
print(df_clean["Contract"].unique())
print(df_clean["Payment Method"].unique())

<ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str
<ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [37]:
# separate categorical and numerical columns
categorical_cols = df_clean.select_dtypes(include=["object", "string"]).columns
numerical_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns

print("Categorical Columns: ", categorical_cols)
print("\nNumerical Columns: ", numerical_cols)

Categorical Columns:  Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method'],
      dtype='str')

Numerical Columns:  Index(['Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Value'], dtype='str')

In [39]:
for col in categorical_cols:
    print(f"\n{col}:")
    print(df_clean[col].unique())
    print("-" * 50)

Gender:
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
--------------------------------------------------

Senior Citizen:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Partner:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Dependents:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

Phone Service:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------

Multiple Lines:
<ArrowStringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str
--------------------------------------------------

Internet Service:
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
--------------------------------------------------

Online Security:
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Online Backup:
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Device Protection:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Tech Support:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Streaming TV:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Streaming Movies:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------

Contract:
<ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str
--------------------------------------------------

Paperless Billing:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------

Payment Method:
<ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
--------------------------------------------------

In [41]:
# encoding categorical columns, dummies takes textcategories and converts them into numbers
df_encoded = pd.get_dummies(df_clean, columns=categorical_cols, drop_first=True, dtype=int)

In [42]:
df_encoded.shape

(7032, 31)

In [43]:
df_encoded.head()

,Tenure Months,Monthly Charges,Total Charges,Churn Value,Gender_Male,Senior Citizen_Yes,Partner_Yes,Dependents_Yes,Phone Service_Yes,Multiple Lines_No phone service,...,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,2,53.85,108.15,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1,2,70.70,151.65,1,0,0,0,1,1,0,...,0,0,0,0,0,0,1,0,1,0
2,8,99.65,820.50,1,0,0,0,1,1,0,...,0,1,0,1,0,0,1,0,1,0
3,28,104.80,3046.05,1,0,0,1,1,1,0,...,0,1,0,1,0,0,1,0,1,0
4,49,103.70,5036.30,1,1,0,0,1,1,0,...,0,1,0,1,0,0,1,0,0,0

In [44]:
df_encoded.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Tenure Months                           7032 non-null   int64
 1   Monthly Charges                         7032 non-null   float64
 2   Total Charges                           7032 non-null   float64
 3   Churn Value                             7032 non-null   int64
 4   Gender_Male                             7032 non-null   int64
 5   Senior Citizen_Yes                      7032 non-null   int64
 6   Partner_Yes                             7032 non-null   int64
 7   Dependents_Yes                          7032 non-null   int64
 8   Phone Service_Yes                       7032 non-null   int64
 9   Multiple Lines_No phone service         7032 non-null   int64
 10  Multiple Lines_Yes                      7032 non-null   int64
 11  Internet Service_Fiber optic            7032 non-null   int64
 12  Internet Service_No                     7032 non-null   int64
 13  Online Security_No internet service     7032 non-null   int64
 14  Online Security_Yes                     7032 non-null   int64
 15  Online Backup_No internet service       7032 non-null   int64
 16  Online Backup_Yes                       7032 non-null   int64
 17  Device Protection_No internet service   7032 non-null   int64
 18  Device Protection_Yes                   7032 non-null   int64
 19  Tech Support_No internet service        7032 non-null   int64
 20  Tech Support_Yes                        7032 non-null   int64
 21  Streaming TV_No internet service        7032 non-null   int64
 22  Streaming TV_Yes                        7032 non-null   int64
 23  Streaming Movies_No internet service    7032 non-null   int64
 24  Streaming Movies_Yes                    7032 non-null   int64
 25  Contract_One year                       7032 non-null   int64
 26  Contract_Two year                       7032 non-null   int64
 27  Paperless Billing_Yes                   7032 non-null   int64
 28  Payment Method_Credit card (automatic)  7032 non-null   int64
 29  Payment Method_Electronic check         7032 non-null   int64
 30  Payment Method_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB